
x = 11
fun void nazwaFunkcji{
    read int i
    while(i < 15){
        read int i
    }
    u = 111
    print u
    }
fun void nazwaFunkcjiNowa{
    u = 222
    print u
    s = 10.1
    e = 11.1
    print e
}
x = 323
print x
ee = 10.111


yy = 121.213312

gg = 8787.312
print gg
ww = 20+(29*30)*21
print ww
bb = (20.1+32.32)/43.1+12.32
print bb
bb = 9999.99
print bb
ffun  nazwaFunkcji
ffun  nazwaFunkcjiNowa


