
x = 11
fun void nazwaFunkcji{
    read real i
    if(i == 5.0){
        print i
        while(i < 15.0){
            read real i
            if(i>10.0){
                print i
            }
        }
    }
    u = 111
    print u
    }
fun void nazwaFunkcjiNowa{
    u = 222
    print u
    s = 10.1
    e = 11.1
    print e
    read int i
    if(i < 10){
        print i
        while(i < 300){
            read int i
            if(i > 150){
                print i
            }
        }
    }

}
x = 323
print x
ee = 10.111


yy = 121.213312

gg = 8787.312
print gg
ww = 20+(29*30)*21
print ww
bb = (20.1+32.32)/43.1+12.32
print bb

ffun  nazwaFunkcji
ffun  nazwaFunkcjiNowa
bb = 999.0
print bb
read real q
while(q<10.0){
    print q
    q++
}

