x = 11
fun void nazwaFunkcji{
    u = 111
    print u
    }
fun void nazwaFunkcjiNowa{
    u = 222
    print u
    s = 10.1
    e = 11.1

    if(e>s){
        a = 1122222
        print a
        read real r
        print r
    }

    print e
}
x = 323
print x
ee = 10.111


yy = 121.213312
if(ee<yy){
    read real gg
    print gg
    read real gg
    print gg
    gg = 123.123
    print gg
}
gg = 8787.312
print gg
ffun  nazwaFunkcji
ffun  nazwaFunkcjiNowa
ww = 20+(29*30)*21
print ww
bb = (20.1+32.32)/43.1+12.32
print bb

