print x
print dasdsdas
print dadas[32]

string dsa = "dsada"

array x = [dsa,adsdsa,"dasdas", 32,213]
if(a==4)
{
print x
print dasdsdas
print dadas[32]
}else{
print dadas[32]
string x = read
int x = read
string dsa = "dsada"

array x = [dsa,adsdsa,"dasdas", 32,213]
int x = 3*3*3/(2332)
}

fun string funkcja(int a, int b, string cadsa)

{

print x
print dasdsdas
print dadas[32]
if(3>4){}

if(fdsa<213){
print zzz
}
string dsa = "dsada"

array x = [dsa,adsdsa,"dasdas", 32,213]
int x = 3*3*3/(2332)
}
while(i<54){
print x
print dasdsdas
}




